spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - Origin
              - Content-Type
              - Accept
              - Authorization
              - User-Key
              - Request-Tracker
              - Session-Tracker
              - X-XSRF-TOKEN
              - X-IBM-CLIENT-ID
              - Message-ID
              - X-IBM-CLIENT-SECRET
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE